#                                DATA ANALYSIS MID PROJECT

In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

## step 1: Load the data

In [15]:
df_adverse_events = pd.read_csv('adverse_events.csv')
df_drugs = pd.read_csv("drugs_overview.csv")
df_prices = pd.read_csv("stock_prices.csv")
df_adverse_events.head()

,safetyreportid,generic_name,brand_queried,receive_date,country,serious,seriousness_death,seriousness_lifethreatening,seriousness_hospitalization,seriousness_disabling,patient_age,patient_age_unit,patient_sex,patient_weight_kg,reaction,reaction_outcome
0,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Stenosis,Unknown
1,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Hunger,Unknown
2,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Visual impairment,Unknown
3,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Incorrect dose administered,Unknown
4,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,81.0,Year,Female,NaN,Inappropriate schedule of product administration,Unknown

In [18]:
# to load drugs overview data

df = df_adverse_events.merge(df_drugs, on="generic_name", how="left")
df.head()

,safetyreportid,generic_name,brand_queried,receive_date,country,serious,seriousness_death,seriousness_lifethreatening,seriousness_hospitalization,seriousness_disabling,...,patient_sex,patient_weight_kg,reaction,reaction_outcome,brand_names,manufacturer,indication,fda_first_approval_date,is_investigational,drug_class
0,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,...,Female,NaN,Stenosis,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist
1,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,...,Female,NaN,Hunger,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist
2,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,...,Female,NaN,Visual impairment,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist
3,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,...,Female,NaN,Incorrect dose administered,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist
4,10188271,semaglutide,OZEMPIC,2014-05-22,US,True,False,False,True,True,...,Female,NaN,Inappropriate schedule of product administration,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,False,GLP-1 receptor agonist

In [19]:
# to show all columns in the dataframe

pd.set_option('display.max_columns', None)

## step 2 : Data description / understanding

| Column Name | Description |
|---|---|
| `safetyreportid` | Unique identifier for the safety report. |
| `generic_name` | Generic name of the reported drug. |
| `brand_queried` | Brand name associated with the reported drug. |
| `receive_date` | Date when the adverse-event report was received. |
| `country` | Country associated with the adverse-event report. |
| `serious` | Indicates whether the reported event was classified as serious. |
| `seriousness_death` | Indicates whether the event resulted in death. |
| `seriousness_lifethreatening` | Indicates whether the event was considered life-threatening. |
| `seriousness_hospitalization` | Indicates whether the event resulted in or required hospitalization. |
| `seriousness_disabling` | Indicates whether the event resulted in disability or incapacity. |
| `patient_age` | Age of the patient at the time of the report. |
| `patient_age_unit` | Unit used to report the patient's age. |
| `patient_sex` | Sex of the patient. |
| `patient_weight_kg` | Patient body weight in kilograms. |
| `reaction` | Reported adverse reaction or event. |
| `reaction_outcome` | Outcome of the reported reaction. |
| `brand_names` | Brand names associated with the drug. |
| `manufacturer` | Pharmaceutical company that manufactures or develops the drug. |
| `indication` | Medical condition(s) or purpose(s) for which the drug is used or investigated. |
| `fda_first_approval_date` | Date when the drug first received FDA approval. |
| `is_investigational` | Indicates whether the drug is investigational rather than approved. |
| `drug_class` | Pharmacological class or type of the drug. |

## step 3 : Data Exploration

In [20]:
# check data types

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 149209 entries, 0 to 149208
Data columns (total 22 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   safetyreportid               149209 non-null  int64
 1   generic_name                 149209 non-null  str
 2   brand_queried                149209 non-null  str
 3   receive_date                 149209 non-null  str
 4   country                      149209 non-null  str
 5   serious                      149209 non-null  bool
 6   seriousness_death            149209 non-null  bool
 7   seriousness_lifethreatening  149209 non-null  bool
 8   seriousness_hospitalization  149209 non-null  bool
 9   seriousness_disabling        149209 non-null  bool
 10  patient_age                  94392 non-null   float64
 11  patient_age_unit             149209 non-null  str
 12  patient_sex                  149209 non-null  str
 13  patient_weight_kg            44716 non-null   float64
 14  reaction                     149209 non-null  str
 15  reaction_outcome             149209 non-null  str
 16  brand_names                  149209 non-null  str
 17  manufacturer                 149209 non-null  str
 18  indication                   149209 non-null  str
 19  fda_first_approval_date      149209 non-null  str
 20  is_investigational           149209 non-null  bool
 21  drug_class                   149209 non-null  str
dtypes: bool(6), float64(2), int64(1), str(13)
memory usage: 19.1 MB

In [25]:
# Check duplicates

print(df.duplicated().sum())

0

In [22]:
# Check summary statistics for Numerical columns

df.describe().round(2)

       safetyreportid  patient_age  patient_weight_kg
count       149209.00     94392.00           44716.00
mean      16084752.11        56.44             107.97
std        5039507.69        13.06            1007.79
min       10005908.00         0.00               1.70
25%       11405367.00        48.00              79.40
50%       14893477.00        57.60              93.96
75%       21374595.00        66.00             109.00
max       24857834.00       100.00           87075.00

In [24]:
# Check summary statistics for Categorical columns

df.describe(include= ['string']).round(2)

,generic_name,brand_queried,receive_date,country,patient_age_unit,patient_sex,reaction,reaction_outcome,brand_names,manufacturer,indication,fda_first_approval_date,drug_class
count,149209,149209,149209,149209,149209,149209,149209,149209,149209,149209,149209,149209,149209
unique,7,12,2947,73,3,3,4604,6,7,5,2,7,3
top,semaglutide,BYETTA,2014-05-10,US,Year,Female,Nausea,Unknown,OZEMPIC; WEGOVY; RYBELSUS,Novo Nordisk,type-2-diabetes/obesity,2017-12-05,GLP-1 receptor agonist
freq,45818,17383,4239,126927,94397,97614,7629,90845,45818,72265,94121,45818,114517

In [26]:
# Check missing values

df.isna().sum()

safetyreportid                      0
generic_name                        0
brand_queried                       0
receive_date                        0
country                             0
serious                             0
seriousness_death                   0
seriousness_lifethreatening         0
seriousness_hospitalization         0
seriousness_disabling               0
patient_age                     54817
patient_age_unit                    0
patient_sex                         0
patient_weight_kg              104493
reaction                            0
reaction_outcome                    0
brand_names                         0
manufacturer                        0
indication                          0
fda_first_approval_date             0
is_investigational                  0
drug_class                          0
dtype: int64

## step 4 : Data cleaning

In [27]:
df.columns

Index(['safetyreportid', 'generic_name', 'brand_queried', 'receive_date',
       'country', 'serious', 'seriousness_death',
       'seriousness_lifethreatening', 'seriousness_hospitalization',
       'seriousness_disabling', 'patient_age', 'patient_age_unit',
       'patient_sex', 'patient_weight_kg', 'reaction', 'reaction_outcome',
       'brand_names', 'manufacturer', 'indication', 'fda_first_approval_date',
       'is_investigational', 'drug_class'],
      dtype='str')

In [35]:
# 1) Investigate the age and age unit columns to see if there are any inconsistencies or missing values.

df['patient_age_unit'].value_counts()

patient_age_unit
Year       94397
Unknown    54810
Decade         2
Name: count, dtype: int64

In [36]:
df['patient_age'].value_counts()

patient_age
62.0    3050
63.0    3002
55.0    2853
61.0    2751
60.0    2723
        ...
37.5       1
38.7       1
83.7       1
40.1       1
78.3       1
Name: count, Length: 464, dtype: int64

In [39]:
px.histogram(df, x="patient_age", color="patient_age_unit", title="Distribution of Patient Age by Age Unit", nbins=50)

In [31]:
# find the decades in the patient_age_unit column
df[df["patient_age_unit"] == "Decade"][["patient_age", "patient_age_unit"]]

       patient_age patient_age_unit
37803          NaN           Decade
37804          NaN           Decade